apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: nkenenbayev-service-api
  description: The official CE NEXTGEN service REST APIs
spec:
  type: openapi
  lifecycle: production
  owner: TeamA
  definition:
    $text: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.json
